// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LegacyLSPAssets: typeof import('./src/components/received/LegacyLSPAssets.vue')['default']
    LSP10Vault: typeof import('./src/components/vaults/LSP10Vault.vue')['default']
    LSP12CreatedAssets: typeof import('./src/components/created/LSP12CreatedAssets.vue')['default']
    LSP5ReceivedAssets: typeof import('./src/components/received/LSP5ReceivedAssets.vue')['default']
    MintNFT: typeof import('./src/components/created/MintNFT.vue')['default']
    MintToken: typeof import('./src/components/created/MintToken.vue')['default']
    NFTAssets: typeof import('./src/components/NFTAssets.vue')['default']
    ProfileInfo: typeof import('./src/components/ProfileInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendAssets: typeof import('./src/components/received/SendAssets.vue')['default']
    TokenAssets: typeof import('./src/components/TokenAssets.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanStep: typeof import('vant/es')['Step']
    VanSteps: typeof import('vant/es')['Steps']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
