// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LSP12CreatedAssets: typeof import('./src/components/LSP12CreatedAssets.vue')['default']
    LSP5ReceivedAssets: typeof import('./src/components/LSP5ReceivedAssets.vue')['default']
    MintNFT: typeof import('./src/components/MintNFT.vue')['default']
    MintToken: typeof import('./src/components/MintToken.vue')['default']
    NFTAssets: typeof import('./src/components/NFTAssets.vue')['default']
    ProfileInfo: typeof import('./src/components/ProfileInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendAssets: typeof import('./src/components/SendAssets.vue')['default']
    TokenAssets: typeof import('./src/components/TokenAssets.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanStep: typeof import('vant/es')['Step']
    VanSteps: typeof import('vant/es')['Steps']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
